= Yip Seng Yeun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ConTAct

---

== Overview

ConTAct is an application designed to help teaching assistants manage the details of their students. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java.

== Summary of contributions

* *Major enhancement*: Ability to add students to a temporary group and perform batch operations on the group
** What it does: allows the user to create temporary groups of students and manipulate these groups using set operations (union, intersection) and run commands on groups of students instead of one by one
** Justification: This enhancement saves time and improves productivity as the user only has to run one command for each batch, instead of one command for every student
** Highlights: Greatly improves usability. Enhances other commands/features.


* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=alyip98[Link]

* *Other contributions*:

** Minor enhancement: added a `tag` command to update tags of a group of students
** Project management:
*** Maintain issue tracker
*** Populate SampleData
*** Assist GUI redesign
*** Review team pull requests
*** Assist team in debugging other features
** Enhancements to existing features:
*** added ability to `find` by tag
** Documentation:
*** Review other members' documentation and suggest improvements
** Community:
** Tools:
*** Tweaked Travis CI build settings to forgive trivial errors (e.g. incorrect alphabetical order of imports will now only give a warning)

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=group]

include::../UserGuide.adoc[tag=cmdtag]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=groupfeature]