= Preethi Devarajan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ConTAct

---

== Overview

ConTAct is a desktop application designed to help teaching assistants by providing them with multiple features that are
catered specifically to easing student management.

Tutors interact with the application through the CLI, and the GUI is implemented using JavaFX. The app itself is written in Java.

== Summary of contributions

* *Major Enhancement*: added Email feature in ConTAct
** What it does: allows the user to email a student directly from the application through an input to the CLI
** Justification: this feature significantly enhances the product by easing the process of emailing a student,
making it quicker.
** Highlights: The feature includes a simple `email` command with which the subject and content can all be set,
just through a single command. It required an in-depth anaylsis of how working with REST-ful API worked,
and how to integrate it with a native application. It was a challenge to make it allow any NUS Outlook user be
able to sign-in with his/her email and send an email to their student. Other challenges included ensuring security, receiving permission from users, and understanding the flow of the authorization-code grant method of getting an access token.

** Credits: The Outlook API usage online provided by Outlook itself served as a good guidance in implementing this.

* Code contributed: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=preethi-d&sort=displayName&since=2018-09-12&until=2018-11-09&timeframe=day&reverse=false&repoSort=true[RepoSense Report]

* *Other Contributions*:

** Project Management:
*** Managed the team and reminded members of deadlines, keeping them on track.
** Community:
*** PRs reviewed: (Pull requests
https://github.com/CS2103-AY1819S1-W13-3/main/pull/31[#31]
https://github.com/CS2103-AY1819S1-W13-3/main/pull/73[#73]
https://github.com/CS2103-AY1819S1-W13-3/main/pull/82[#82])
*** Updated Documentation and sequence diagrams: (Pull requests
https://github.com/CS2103-AY1819S1-W13-3/main/pull/23[#23]
https://github.com/CS2103-AY1819S1-W13-3/main/pull/69[#69]
https://github.com/CS2103-AY1819S1-W13-3/main/pull/44[#44])
*** Reported bugs in the PE dry run. (Issues for
https://github.com/CS2103-AY1819S1-T13-2/main/issues/93[#93]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/92[#92]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/90[#90]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/89[#89]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/86[#86]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/85[#85]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/83[#83]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/82[#82]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/88[#88]
https://github.com/CS2103-AY1819S1-T13-2/main/issues/84[#84])

== Contributions to User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=email]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=email]
include::../DeveloperGuide.adoc[tag=emailUseCase]

Manual Test:
include::../DeveloperGuide.adoc[tag=emailManualTest]
